### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rabidsheep** [kokonguyen191/Hoshimori-Scrapy#1]
when i run get_database_zh.py in Python3.6 initially i get this error:

> Traceback (most recent call last):
>   File "C:\Miniconda3\envs\bghsenv\lib\site-packages\scrapy\core\engine.py", line 127, in _next_request
>     request = next(slot.start_requests)
>   File "C:\Users\nibutaniSNK\Downloads\Hoshimori-Scrapy-master\hoshimori\hoshimori\spiders\card_database_zh_spider.py", line 38, in start_requests
>     next(f)
>   File "C:\Users\nibutaniSNK\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 54: character maps to `<undefined>`

i can get past it by adding encoding='utf8' to `open(self.middle_file)` in card_database_zh_spider.py, but then i get this error which i cannot seem to get past:

> Traceback (most recent call last):
>   File "C:\Miniconda3\envs\bghsenv\lib\site-packages\scrapy\core\engine.py", line 127, in _next_request
>     request = next(slot.start_requests)
>   File "C:\Users\nibutaniSNK\Downloads\Hoshimori-Scrapy-master\hoshimori\hoshimori\spiders\card_database_zh_spider.py", line 40, in start_requests
>     yield scrapy.Request(url + row[2], callback=self.parse,
> IndexError: list index out of range
 
the only other modifications i've done to the scripts are changing the instances of `print err.args` to `print(err.args)` and adding sys.path.append in get_database_zh.py to add the virtual environment directories to the interpreter's search path.

**Comment by rabidsheep** [comment]
went back and tried again today. it's because on windows a newline is added between every row in csv files when they're read. adding newline='' to open() didn't work, but adding an if-else condition to skip rows with a length of 1 or less did:
```python
for row in reader:
    if len(row) <= 1:
        pass
    else:
        yield scrapy.Request(url + row[2], callback=self.parse, meta={'id': row[0],
                                          'japanese_name': row[1], 'image': row[3],
                                          'special_icon': row[4]})
```
i'm an idiot, oops
